App\Request\UploadImageRequest:
  properties:
    uploadedFile:
      - Image:
          #mimeTypesMessage: "this id not message"
          maxSize: 2m
          maxSizeMessage: "Image size over 2M"

App\Request\CreateImageRequest:
  properties:
    image:
      - NotBlank: ~
    entity:
      - NotBlank: ~
    itemID:
      - NotBlank: ~

App\Request\UpdateImageRequest:
  properties:
    image:
      - NotBlank: ~

App\Request\PackageCreateRequest:
  properties:
    name:
      - NotBlank: ~
    cost:
      - NotBlank: ~
    carCount:
      - NotBlank: ~
    orderCount:
      - NotBlank: ~
    city:
      - NotBlank: ~
    status:
      - NotBlank: ~

App\Request\PackageUpdateRequest:
  properties:
    id:
      - NotBlank: ~
    name:
      - NotBlank: ~
    cost:
      - NotBlank: ~
    carCount:
      - NotBlank: ~
    orderCount:
      - NotBlank: ~
    city:
      - NotBlank: ~
    status:
      - NotBlank: ~

App\Request\SubscriptionCreateRequest:
  properties:
    ownerID:
      - NotBlank: ~
    packageID:
      - NotBlank: ~
    status:
      - NotBlank: ~

App\Request\UserRegisterRequest:
  properties:
    userID:
      - NotBlank: ~
    password:
      - NotBlank: ~

App\Request\UserProfileCreateRequest:
  properties:
    userID:
      - NotBlank: ~
    userName:
      - NotBlank: ~

App\Request\UserProfileUpdateeRequest:
  properties:
    id:
      - NotBlank: ~
    userID:
      - NotBlank: ~
    userName:
      - NotBlank: ~