App\Request\UploadImageRequest:
  properties:
    uploadedFile:
      - Image:
          #mimeTypesMessage: "this id not message"
          maxSize: 2m
          maxSizeMessage: "Image size over 2M"

App\Request\CreateImageRequest:
  properties:
    image:
      - NotBlank: ~
    entity:
      - NotBlank: ~
    itemID:
      - NotBlank: ~

App\Request\UpdateImageRequest:
  properties:
    image:
      - NotBlank: ~

App\Request\PackageCreateRequest:
  properties:
    name:
      - NotBlank: ~
    cost:
      - NotBlank: ~
    carCount:
      - NotBlank: ~
    orderCount:
      - NotBlank: ~
    city:
      - NotBlank: ~
    status:
      - NotBlank: ~
    branch:
      - NotBlank: ~

App\Request\PackageUpdateRequest:
  properties:
    id:
      - NotBlank: ~
    name:
      - NotBlank: ~
    cost:
      - NotBlank: ~
    carCount:
      - NotBlank: ~
    orderCount:
      - NotBlank: ~
    city:
      - NotBlank: ~
    status:
      - NotBlank: ~
    branch:
      - NotBlank: ~

App\Request\SubscriptionCreateRequest:
  properties:
    packageID:
      - NotBlank: ~

App\Request\SubscriptionUpdateRequest:
  properties:
    packageID:
      - NotBlank: ~
    status:
      - NotBlank: ~
    endDate:
      - NotBlank: ~

App\Request\UserRegisterRequest:
  properties:
    userID:
      - NotBlank: ~
    password:
      - NotBlank: ~

App\Request\UserProfileCreateRequest:
  properties:
    userID:
      - NotBlank: ~
    userName:
      - NotBlank: ~

App\Request\UserProfileUpdateeRequest:
  properties:
    id:
      - NotBlank: ~
    userID:
      - NotBlank: ~
    userName:
      - NotBlank: ~

App\Request\OrderCreateRequest:
  properties:
    source:
      - NotBlank: ~
    destination:
      - NotBlank: ~
    note:
      - NotBlank: ~
    payment:
      - NotBlank: ~
   

App\Request\OrderUpdateRequest:
  properties:
    id:
      - NotBlank: ~
    source:
      - NotBlank: ~
    destination:
      - NotBlank: ~
    note:
      - NotBlank: ~
    payment:
      - NotBlank: ~
    state:
      - NotBlank: ~

App\Request\AcceptedOrderCreateRequest:
  properties:
    orderID:
      - NotBlank: ~
    cost:
      - NotBlank: ~
    duration:
      - NotBlank: ~

App\Request\AcceptedOrderUpdateRequest:
  properties:
    id:
      - NotBlank: ~
    orderID:
      - NotBlank: ~
    cost:
      - NotBlank: ~